# Generated by Django 5.1.3 on 2024-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('storeUrl', models.URLField()),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('livingroom', 'Living Room'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('playroom', 'Playroom'), ('kitchen', 'Kitchen'), ('backyard', 'Backyard'), ('office', 'Office'), ('balcony', 'Balcony'), ('other', 'Other')], max_length=10)),
            ],
        ),
    ]
