# Generated by Django 5.1.3 on 2024-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planlist', '0003_alter_wishlist_storeurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trailerLink', models.URLField(blank=True, max_length=2000)),
                ('image', models.URLField(blank=True, max_length=2000)),
                ('mainGenre', models.CharField(blank=True, choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('SCIFI', 'Science Fiction'), ('FANTASY', 'Fantasy'), ('DOCUMENTARY', 'Documentary'), ('other', 'Other')], max_length=20)),
                ('subGenre', models.CharField(blank=True, choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('SCIFI', 'Science Fiction'), ('FANTASY', 'Fantasy'), ('DOCUMENTARY', 'Documentary'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
